; 타임 트래커 읽기 전용 파일, 프로세스에 대한 한글명 변형출력

[Alias]
chrome=크롬
explorer.exe=파일 탐색기
explorer=파일 탐색기
afterfx=에프터이펙트
photoshop=포토샵
moho=모호
premiere=프리미어
animate=애니메이트
slack=슬랙
Kartdrift-win64-shipping=카트라이더
clipstudiopaint=클립스튜디오
code=코딩
notepad=메모장
afk=자리비움
autohotkey64=오토핫키